/**
 * BOB — Dados de demonstração para o Motor (Fase 3)
 *
 * Simula um snapshot de rodada com 10 jogos do Brasileirão Série A.
 * Na Fase 4, esses dados virão dos conectores de API
 * (football-data.org, API-Football, TheSportsDB).
 *
 * Cada objeto satisfaz o contrato MatchInput do engine.
 */

import { type MatchInput } from "./engine";

export const DEMO_ROUND_LABEL = "Rodada 15 — 2026";
export const DEMO_FIRST_MATCH = "Sáb 17/05 às 16:00";
export const DEMO_CUTOFF = "Sáb 17/05 às 15:00";

export const demoMatches: MatchInput[] = [
  // ── Âncoras esperadas (score elevado) ─────────────────────────────────────
  {
    id: "m01",
    match: "Flamengo x Juventude",
    homeTeam: "Flamengo",
    awayTeam: "Juventude",
    homePosition: 2,
    awayPosition: 18,
    homeNeedsWin: false,
    awayNeedsWin: true,
    homeForm: ["W", "W", "W", "D", "W"],
    awayForm: ["L", "L", "D", "L", "L"],
    homeHomePoints: 13,
    awayAwayPoints: 2,
    homeGoalsScored5: 11,
    homeGoalsConceded5: 3,
    awayGoalsScored5: 3,
    awayGoalsConceded5: 12,
    h2hHomeWinRate: 0.8,
    homeAbsenceRate: 0.05,
    awayAbsenceRate: 0.35,
    homeBigGameAhead: false,
    awayBigGameAhead: false,
    homeOdd: 1.44,
    drawOdd: 4.10,
    awayOdd: 7.00,
    homeOddDropped: true,
  },
  {
    id: "m02",
    match: "Palmeiras x Vitória",
    homeTeam: "Palmeiras",
    awayTeam: "Vitória",
    homePosition: 1,
    awayPosition: 17,
    homeNeedsWin: false,
    awayNeedsWin: false,
    homeForm: ["W", "W", "D", "W", "W"],
    awayForm: ["L", "D", "L", "L", "D"],
    homeHomePoints: 14,
    awayAwayPoints: 3,
    homeGoalsScored5: 9,
    homeGoalsConceded5: 2,
    awayGoalsScored5: 4,
    awayGoalsConceded5: 10,
    h2hHomeWinRate: 0.8,
    homeAbsenceRate: 0.05,
    awayAbsenceRate: 0.25,
    homeBigGameAhead: false,
    awayBigGameAhead: false,
    homeOdd: 1.55,
    drawOdd: 3.90,
    awayOdd: 5.50,
    homeOddDropped: true,
  },
  {
    id: "m03",
    match: "Botafogo x Cuiabá",
    homeTeam: "Botafogo",
    awayTeam: "Cuiabá",
    homePosition: 3,
    awayPosition: 19,
    homeNeedsWin: false,
    awayNeedsWin: true,
    homeForm: ["W", "D", "W", "W", "W"],
    awayForm: ["L", "L", "L", "D", "L"],
    homeHomePoints: 11,
    awayAwayPoints: 1,
    homeGoalsScored5: 8,
    homeGoalsConceded5: 4,
    awayGoalsScored5: 3,
    awayGoalsConceded5: 11,
    h2hHomeWinRate: 0.6,
    homeAbsenceRate: 0.1,
    awayAbsenceRate: 0.4,
    homeBigGameAhead: false,
    awayBigGameAhead: false,
    homeOdd: 1.67,
    drawOdd: 3.60,
    awayOdd: 5.00,
    homeOddDropped: false,
  },
  {
    id: "m04",
    match: "Cruzeiro x Atlético-GO",
    homeTeam: "Cruzeiro",
    awayTeam: "Atlético-GO",
    homePosition: 5,
    awayPosition: 20,
    homeNeedsWin: false,
    awayNeedsWin: true,
    homeForm: ["W", "W", "D", "W", "D"],
    awayForm: ["L", "D", "L", "L", "L"],
    homeHomePoints: 10,
    awayAwayPoints: 2,
    homeGoalsScored5: 7,
    homeGoalsConceded5: 4,
    awayGoalsScored5: 3,
    awayGoalsConceded5: 9,
    h2hHomeWinRate: 0.6,
    homeAbsenceRate: 0.1,
    awayAbsenceRate: 0.3,
    homeBigGameAhead: false,
    awayBigGameAhead: false,
    homeOdd: 1.74,
    drawOdd: 3.40,
    awayOdd: 4.80,
    homeOddDropped: true,
  },

  // ── Preenchimentos (score intermediário) ───────────────────────────────────
  {
    id: "m05",
    match: "Fortaleza x Athletico-PR",
    homeTeam: "Fortaleza",
    awayTeam: "Athletico-PR",
    homePosition: 6,
    awayPosition: 10,
    homeNeedsWin: false,
    awayNeedsWin: false,
    homeForm: ["W", "D", "W", "D", "W"],
    awayForm: ["D", "W", "L", "D", "W"],
    homeHomePoints: 9,
    awayAwayPoints: 6,
    homeGoalsScored5: 6,
    homeGoalsConceded5: 5,
    awayGoalsScored5: 5,
    awayGoalsConceded5: 6,
    h2hHomeWinRate: 0.4,
    homeAbsenceRate: 0.1,
    awayAbsenceRate: 0.1,
    homeBigGameAhead: false,
    awayBigGameAhead: true,
    homeOdd: 1.98,
    drawOdd: 3.20,
    awayOdd: 3.80,
    homeOddDropped: false,
  },
  {
    id: "m06",
    match: "Internacional x Vasco",
    homeTeam: "Internacional",
    awayTeam: "Vasco",
    homePosition: 7,
    awayPosition: 13,
    homeNeedsWin: false,
    awayNeedsWin: false,
    homeForm: ["W", "W", "D", "L", "W"],
    awayForm: ["L", "D", "D", "W", "L"],
    homeHomePoints: 9,
    awayAwayPoints: 5,
    homeGoalsScored5: 7,
    homeGoalsConceded5: 6,
    awayGoalsScored5: 5,
    awayGoalsConceded5: 7,
    h2hHomeWinRate: 0.4,
    homeAbsenceRate: 0.15,
    awayAbsenceRate: 0.2,
    homeBigGameAhead: false,
    awayBigGameAhead: false,
    homeOdd: 1.92,
    drawOdd: 3.30,
    awayOdd: 4.10,
    homeOddDropped: false,
  },
  {
    id: "m07",
    match: "Bragantino x Grêmio",
    homeTeam: "Bragantino",
    awayTeam: "Grêmio",
    homePosition: 8,
    awayPosition: 11,
    homeNeedsWin: false,
    awayNeedsWin: false,
    homeForm: ["D", "W", "D", "W", "D"],
    awayForm: ["W", "D", "D", "L", "D"],
    homeHomePoints: 8,
    awayAwayPoints: 6,
    homeGoalsScored5: 5,
    homeGoalsConceded5: 4,
    awayGoalsScored5: 5,
    awayGoalsConceded5: 5,
    h2hHomeWinRate: 0.4,
    homeAbsenceRate: 0.1,
    awayAbsenceRate: 0.1,
    homeBigGameAhead: false,
    awayBigGameAhead: false,
    homeOdd: 2.02,
    drawOdd: 3.18,
    awayOdd: 3.42,
    homeOddDropped: false,
  },

  // ── Jogos mais equilibrados / "sujos" ──────────────────────────────────────
  {
    id: "m08",
    match: "Bahia x Corinthians",
    homeTeam: "Bahia",
    awayTeam: "Corinthians",
    homePosition: 9,
    awayPosition: 12,
    homeNeedsWin: false,
    awayNeedsWin: false,
    homeForm: ["D", "W", "L", "D", "W"],
    awayForm: ["D", "L", "W", "D", "D"],
    homeHomePoints: 7,
    awayAwayPoints: 6,
    homeGoalsScored5: 5,
    homeGoalsConceded5: 5,
    awayGoalsScored5: 5,
    awayGoalsConceded5: 6,
    h2hHomeWinRate: 0.4,
    homeAbsenceRate: 0.2,
    awayAbsenceRate: 0.2,
    homeBigGameAhead: false,
    awayBigGameAhead: false,
    homeOdd: 2.14,
    drawOdd: 3.05,
    awayOdd: 3.40,
    homeOddDropped: false,
  },
  {
    id: "m09",
    match: "Fluminense x São Paulo",
    homeTeam: "Fluminense",
    awayTeam: "São Paulo",
    homePosition: 14,
    awayPosition: 8,
    homeNeedsWin: false,
    awayNeedsWin: false,
    homeForm: ["L", "D", "W", "L", "D"],
    awayForm: ["W", "D", "W", "W", "D"],
    homeHomePoints: 5,
    awayAwayPoints: 8,
    homeGoalsScored5: 4,
    homeGoalsConceded5: 7,
    awayGoalsScored5: 7,
    awayGoalsConceded5: 4,
    h2hHomeWinRate: 0.4,
    homeAbsenceRate: 0.2,
    awayAbsenceRate: 0.1,
    homeBigGameAhead: false,
    awayBigGameAhead: true,
    homeOdd: 2.60,
    drawOdd: 3.12,
    awayOdd: 2.55,
    homeOddDropped: false,
  },
  {
    id: "m10",
    match: "Atlético-MG x Santos",
    homeTeam: "Atlético-MG",
    awayTeam: "Santos",
    homePosition: 4,
    awayPosition: 16,
    homeNeedsWin: false,
    awayNeedsWin: false,
    homeForm: ["D", "W", "L", "W", "D"],
    awayForm: ["L", "W", "L", "D", "L"],
    homeHomePoints: 8,
    awayAwayPoints: 3,
    homeGoalsScored5: 6,
    homeGoalsConceded5: 6,
    awayGoalsScored5: 4,
    awayGoalsConceded5: 8,
    h2hHomeWinRate: 0.5,
    homeAbsenceRate: 0.25,
    awayAbsenceRate: 0.2,
    homeBigGameAhead: true,
    awayBigGameAhead: false,
    homeOdd: 1.88,
    drawOdd: 3.08,
    awayOdd: 4.20,
    homeOddDropped: false,
  },
];
